---
- name: Download and install or update packages using dpkg
  hosts: localhost
  become: yes
  tasks:
    - name: Create /opt/deb_dl/
      ansible.builtin.file:
        path: /opt/deb_dl
        state: directory

    - name: Download Google Chrome
      ansible.builtin.get_url:
        url: "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
        dest: /opt/deb_dl/google-chrome-stable_current_amd64.deb
        backup: true
      register: last_dl

    - name: Install or update Google Chrome
      ansible.builtin.apt:
        deb: /opt/deb_dl/google-chrome-stable_current_amd64.deb
        state: present
      when: last_dl.changed

    - name: Download Zoom
      ansible.builtin.get_url:
        url: "https://zoom.us/client/latest/zoom_amd64.deb"
        dest: /opt/deb_dl/zoom_amd64.deb
        backup: true
      register: last_dl

    - name: Install or update Zoom
      ansible.builtin.apt:
        deb: /opt/deb_dl/zoom_amd64.deb
        state: present
      when: last_dl.changed

    - name: Download Rambox
      ansible.builtin.get_url:
        url: "https://rambox.app/api/download?os=linux&package=deb"
        dest: /opt/deb_dl/rambox.deb
        backup: true
      register: last_dl

    - name: Install or update Rambox
      ansible.builtin.apt:
        deb: /opt/deb_dl/rambox.deb
        state: present
      when: last_dl.changed

    - name: Download Discord
      ansible.builtin.get_url:
        url: "https://discord.com/api/download?platform=linux&format=deb"
        dest: /opt/deb_dl/discord.deb
        backup: true
      register: last_dl

    - name: Install or update Discord
      ansible.builtin.apt:
        deb: /opt/deb_dl/discord.deb
        state: present
      when: last_dl.changed

    - name: Download Visual Studio Code
      ansible.builtin.get_url:
        url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
        dest: /opt/deb_dl/vscode.deb
        backup: true
      register: last_dl

    - name: Install or update Visual Studio Code
      ansible.builtin.apt:
        deb: /opt/deb_dl/vscode.deb
        state: present
      when: last_dl.changed

    - name: Install APT packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
      loop:
        - gnome-shell-extension-dashtodock
        - gnome-shell-extension-prefs
        - vlc
        - keepassxc
        - firefox-esr
        - firefox-esr-l10n-de
        - thunderbird
        - thunderbird-l10n-de
        - vim
        - virt-manager
        - remmina
        - curl
        - gpg
        - htop
        - vnstat
        - network-manager-openconnect
        - network-manager-openconnect-gnome
        - nextcloud-desktop
        - nextcloud-desktop-l10n

    - name: "Spotify: Install GPG key"
      ansible.builtin.shell:
        cmd: curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
      args:
        creates: /etc/apt/trusted.gpg.d/spotify.gpg
    - name: "Spotify: Add APT repository"
      ansible.builtin.apt_repository:
        repo: "deb http://repository.spotify.com stable non-free"
        filename: spotify
        state: present
    - name: "Spotify: Install"
      ansible.builtin.apt:
        name: spotify-client
        state: present
